name: Deploy Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted     # Your gitea-runner container
    steps:
      - name: Clear temporary directory
        run: |
          [ -d "/tmp/website" ] && rm -rf /tmp/website

      - name: Clone repository
        run: git clone --depth 1 http://gitea:3000/Jevadmin/WebPageLearning.git /tmp/website

      - name: Clear webserver directory
        run: |
          [ -d "/usr/share/nginx/html" ] && rm -rf /usr/share/nginx/html/*

      - name: Deploy website
        run: cp -r /tmp/website/* /usr/share/nginx/html/